spring:
  application:
    name: drivaltech-finance-api

  datasource:
    url: jdbc:postgresql://localhost:5432/drivaltech
    username: postgres
    password: BdP0sTgRsS@L2026

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true