spring:
  application:
    name: drivaltech-finance-api

  datasource:
    url: jdbc:postgresql://localhost:5432/drivaltech
    username: postgres
    password: BdP0sTgRsS@L2026

  data:

    redis:
      host: host.docker.internal
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

logging:
  level:
    org.springframework.security: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%X{correlationId}] [user=%X{username}] [ip=%X{ip}] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always